---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-app-set-repo-{{ .Values.env }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: {{ .Values.env }} App Set Repo
  url: {{ .Values.argoRepo }}
