---
apiVersion: v1
kind: Secret
metadata:
  name: argo-test-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: Argo Test Repo
  url: {{ .Values.argoRepo }}
