values: |
  nginx-1:
    repoURL: https://github.com/ikatzarski/argocd-app-set.git
    targetRevision: HEAD
    path: ./charts/nginx-1
    env: dev
    namespace: dev
    chartConfig:
      appSelector: nginx-1-dev

      service:
        name: nginx-1-dev
        port: 80

      deployment:
        name: nginx-1-dev
        replicas: 1
        image: nginx
        containerHttpPort: 80
        imagePullPolicy: IfNotPresent

  nginx-2:
    repoURL: https://github.com/ikatzarski/argocd-app-set.git
    targetRevision: HEAD
    path: ./charts/nginx-2
    env: dev
    namespace: dev
    chartConfig:
      appSelector: nginx-2-dev

      service:
        name: nginx-2-dev
        port: 80

      deployment:
        name: nginx-2-dev
        replicas: 1
        image: nginx
        containerHttpPort: 80
        imagePullPolicy: IfNotPresent
